version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./apps/todo:/work
    networks:
      - my-net
  web:
    image: nginx:1.18-alpine
    ports:
      - 10081:80
    volumes: 
      - ./apps/todo:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-net
    working_dir: /work
  db:
    build: ./docker/mysql
    image: mysql:5.7
    container_name: my_db
    restart: always
    networks:
      - my-net
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 3ikN33Himtmu
      MYSQL_ROOT_PASSWORD: 3ikN33Himtmu
      TZ: "Asia/Tokyo"
    ports:
      - "3314:3306"
    command:
        - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/log/mysql:/var/log/mysql
networks:
  my-net:
    driver: bridge
volumes:
  db-store: